scrape_configs:
  - job_name: "Server"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "API"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:3002"]
